apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: dsunitha2/new_backend
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              value: "postgres://postgres:admin123@database-service:5432/basic3tier"

