apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: dsunitha2/frontend-app
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              value: "http://backend-service:8080" # Assuming the backend listens on port 8080

