apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: dsunitha2/new_frontend
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              value: "http://aa816fd168cb143408448849eb08fff8-1808465688.us-east-2.elb.amazonaws.com" # Assuming the backend listens on port 8080

