name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This means deploy will run after build completes successfully.

    steps:
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-2'
        
    - name: Updating the EKS cluster using kubeconfig
      run: aws eks update-kubeconfig --region us-east-2 --name sun-3tier-cluster
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 

    - name: Copying the key pair from GitHub secrets to the EC2 instance
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY_PAIR }}" > ~/.ssh/GFS-kp.pem
        chmod 400 ~/.ssh/GFS-kp.pem

    - name: Add EC2 instance to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

    - name: Clone the repo
      run: |
        ssh -i ~/.ssh/GFS-kp.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          if [ ! -d "3tier_app_aws_eks_cluster/.git" ]; then
            git clone https://github.com/Sunithadodda/3tier_app_aws_eks_cluster.git
          else
            cd 3tier_app_aws_eks_cluster
            git fetch origin
            git checkout main  # or whichever branch you want to track
          fi
        EOF

    - name: Deploy manifests to EKS
      run: |
        cd 3tier_app_aws_eks_cluster
        kubectl apply -f backend-deployment.yml
        kubectl apply -f backend-service.yml
        kubectl apply -f database-deployment.yml
        kubectl apply -f database-service.yml
        kubectl apply -f docker-compose.yml
        kubectl apply -f frontend-deployment.yml
        kubectl apply -f frontend-ingress.yml
        kubectl apply -f frontend-lb-service.yml
        kubectl apply -f frontend-service.yml
        kubectl apply -f postgres-pv.yml
        kubectl apply -f postgres-pvc.yml
