name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker images
      run: |
        docker build -t dsunitha2/new_backend ./api
        docker build -t dsunitha2/new_frontend ./ui
   
    - name: Log on Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker images to Docker Hub
      run: |
        docker push dsunitha2/new_backend
        docker push dsunitha2/new_frontend

