# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Continues Intigration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
   
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the code from the repo

    # Step 2: Set up Docker Buildx (enables multi-platform builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Set up Docker Buildx

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username stored in GitHub Secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password stored in GitHub Secrets

    # Step 4: Build Docker images
    - name: Build Docker images
      run: |
        # Build Docker image for backend
        docker build -t dsunitha2/new_backend ./api
        # Build Docker image for frontend
        docker build -t dsunitha2/new_frontend ./ui

    # Step 5: Push Docker images to Docker Hub
    - name: Push Docker images to Docker Hub
      run: |
        # Push the backend Docker image
        docker push dsunitha2/new_backend
        # Push the frontend Docker image
        docker push dsunitha2/new_frontend
